# Default initial positions for fr3's ros2_control fake system

initial_positions:
  fr3_finger_joint1: 0
  fr3_joint1: 0
  fr3_joint2: 0
  fr3_joint3: 0
  fr3_joint4: -2.3395
  fr3_joint5: 0
  fr3_joint6: 1.6638
  fr3_joint7: 0